listener {
    timeout = 300                                 # 5 menit
    on-timeout = hyprlock                         # Perintah untuk mengunci layar
}

listener {
    timeout = 600                                 # 10 menit
    on-timeout = hyprctl dispatch dpms off        # Mematikan layar untuk hemat daya
    on-resume = hyprctl dispatch dpms on          # Menyalakan kembali saat mouse bergerak
}
