$font-normal = FiraCode Nerd Font
$font-bold    = FiraCode Nerd Font Bold
$clock-color  = rgba(255, 255, 255, 1)
$shadow-pass  = 2
$shadow-size  = 3
$shadow-color = rgb(0,0,0)
$shadow-boost = 1.2
$text-shadow-pass   = 1
$text-shadow-boost  = 0.5

background {
    monitor =
    path = ~/Pictures/wallps/catppucin.png
    blur_passes = 0
    contrast            = 0.8916
    brightness          = 0.7172
    vibrancy            = 0.1696
    vibrancy_darkness   = 0
}

input-field {
    monitor =
    size        = 275, 55
    rounding    =  3
    outline_thickness = 1
    dots_size = 0.1
    dots_spacing = 1
    dots_center = true
    fade_on_empty = false
    font_color = rgb(200, 200, 200)
    inner_color = rgb(20, 20, 20)
    outer_color = rgb(45, 45, 45)
    placeholder_text = <span>󰢏 $USER</span>
    font_family         = $font-normal
    position            = 0, -240
    halign              = center
    valign              = center
    zindex              = 10
}

label {
    monitor     =
    # text        = cmd[update:1000] echo -e "$(date +"%H")" # 24-Hour Format
    text        = cmd[update:1000] echo -e "$(date +"%I")" # 12-Hour Format
    color       = $clock-color
    
    shadow_pass         = $shadow-pass
    shadow_size         = $shadow-size
    shadow_color        = $shadow-color
    shadow_boost        = $shadow-boost
    
    font_size           = 150
    font_family         = $font-bold
    
    position            = 0, -155
    halign              = center
    valign              = top
}

label {
    monitor     =
    text        = cmd[update:1000] echo -e "$(date +"%M")"
    color       = $clock-color
    
    shadow_pass         = $shadow-pass
    shadow_size         = $shadow-size
    shadow_color        = $shadow-color
    shadow_boost        = $shadow-boost

    font_size           = 150
    font_family         = $font-bold
    
    position            = 0, -325
    halign              = center
    valign              = top
}

label {
    monitor     =
    text = cmd[update:1000] echo -e "$(date +"%p")"
    color       = $clock-color
    
    shadow_pass         = $shadow-pass
    shadow_size         = $shadow-size
    shadow_color        = $shadow-color
    shadow_boost        = $shadow-boost

    font_size           = 16
    font_family         = $font-bold
    
    position            = 0, 30
    halign              = center
    valign              = center
    zindex		= 5
}
