background {
    monitor =
    path = /path/to/your/wallpaper.png   # Ubah ke jalur wallpaper Anda
    blur_passes = 2                      # Efek blur modern
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    fade_on_empty = false
    font_color = rgb(200, 200, 200)
    inner_color = rgb(20, 20, 20)
    outer_color = rgb(45, 45, 45)
    placeholder_text = <i>Password...</i>
}
