unbind r
bind r source-file ~/.tmux.conf
bind c new-window -c "$HOME"

set -g prefix C-a

set -g mouse on
set -g status-position top
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'

set -g @catppuccin_flavor "mocha"

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_blue}"
set -g @catppuccin_window_text ""
set -g @catppuccin_window_number "#[bold]Tab ###I "
set -g @catppuccin_window_current_text ""
set -g @catppuccin_window_current_number "#[bold]Tab ###I "
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}] #[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_text_color},fg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_text_color},fg=#{@catppuccin_window_current_number_color}]"

set -g @catppuccin_status_left_separator "#[reverse]#[none]"
set -g @catppuccin_status_middle_separator ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_connect_separator "yes"

run '~/.tmux/plugins/tmux/catppuccin.tmux'

set -g window-status-separator ""
set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#{E:@catppuccin_status_application}"
set -g status-left "#[fg=#{@thm_fg} bold]TMUX: #S | "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_blue} bold]NORMAL }}"
set -g status-right "#[fg=#{@thm_blue} bold] #{pane_current_command} #[fg=#{@thm_fg} bold]|#[fg=#{@thm_blue} bold] %A #[fg=#{@thm_fg} bold]| %d-%m-%Y "

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
